PHP8.4 Support Added
laminas/laminas-json pull request #19
Opened 2024-10-09 09:52 UTC by cod43156

|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

2024-10-11 10:07 UTC, gsteel requested changes
You can ignore platform requirements for 8.4 to get dependencies installed like in this PR: https://github.com/laminas/laminas-mvc-i18n/pull/41/files

You may need to bump `laminas/stdlib` to `3.19.0` minimum for 8.4 compat and you will likely need to bump dev deps with `composer bump -D`

Please also sign off your commits as per the [contributing guide](https://github.com/laminas/.github/blob/main/CONTRIBUTING.md#commit-signoffs)

2024-10-24 14:39 UTC, cod43156 commented
> You can ignore platform requirements for 8.4 to get dependencies installed like in this PR: https://github.com/laminas/laminas-mvc-i18n/pull/41/files
> 
> You may need to bump `laminas/stdlib` to `3.19.0` minimum for 8.4 compat and you will likely need to bump dev deps with `composer bump -D`
> 
> Please also sign off your commits as per the [contributing guide](https://github.com/laminas/.github/blob/main/CONTRIBUTING.md#commit-signoffs)

@gsteel The comment has been resolved. I' ve bumped laminas/stdlib to ^3.19.0 for 8.4 compatibility, and ignored platform requirements.

2024-10-24 14:40 UTC, gsteel commented
Please can you also fix the minor docs linting issues so that we have a green build?

2024-10-24 16:54 UTC, cod43156 commented
> Please can you also fix the minor docs linting issues so that we have a green build?
@gsteel lint issues fixed

2024-10-24 16:57 UTC, samsonasik commented on .laminas-ci.json
> +        "8.4": true
can this only php 8.4?

2024-10-24 17:01 UTC, cod43156 commented on .laminas-ci.json
> +        "8.4": true
8.1 removed

2024-10-24 17:03 UTC, samsonasik approved these changes

2024-10-25 09:01 UTC, gsteel approved these changes
Thanks @cod43156

2024-10-25 09:02 UTC, merged